def skipBuild = true
pipeline {
 agent {
        docker {
            image 'cypress/browsers:latest' 
            args '-v /home:/home/node/ -u root -v /usr/local/bin/docker:/usr/bin/docker -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }
 environment {
        AUTHOR = ''
    }
 stages {
  stage('Checkout') {
   steps {
    checkout scm
   }
  }
  stage('check branch') {
   steps {
    sh 'git --version'
    echo "Branch: ${env.BRANCH_NAME}"
    script {
     def GIT_LOG = sh(script: "git log --oneline -n 1 HEAD --pretty=format:%B", returnStdout: true)
     env.AUTHOR = sh(
        script: "git --no-pager show -s --format='%au'",
        returnStdout: true
       ).trim()
     def message = GIT_LOG.trim().replaceAll("\n ", "")
     echo "GIT_LOG:${message.size()} , ${GIT_LOG}"
     def deployMatch = message ==~/(?i).*deployj#.*/
     echo "deployMatch: ${deployMatch}"
     if (env.BRANCH_NAME == "master") {
      skipBuild = true;
     }
     if (deployMatch) {
      skipBuild = false;
     }
     echo "skipBuild: ${skipBuild}"
    }
   }
  }
  stage('Build') {
   when {
    expression {
     skipBuild == false
    }
   }
   steps {
    //notifyBuild('Build started','');
    //sh '''ssh -i /home/node/.ssh/id_rsa public.tar -t davinderk@10.126.1.6 "docker ps" '''
   // sh 'npm install';
    //sh 'ls /home/node'
    //input message: 'Finished using the web site? (Click "Proceed" to continue)'
    //sh 'ssh -t davinderk@10.126.1.6'
    //sh '''ssh -i /home/node/.ssh/id_rsa davinderk@10.126.1.6 -o "StrictHostKeyChecking no" [[ -f /u01/app/appshare/frontend/deploymentRunning ]] && echo "true" || echo "false"'''
    //sh '''scp -i /home/node/.ssh/id_rsa public.tar davinderk@10.126.1.6:/u01/app/appshare/frontend/'''
   // sh 'npm run build'
    //withCredentials([string(credentialsId: 'docker-hub-password', variable: 'DOCKER_PWD')]) {
    //sh ' docker login -u steltix -p ${DOCKER_PWD}'
  //}
    
    script {
       //docker.withRegistry('https://index.docker.io/v1/', 'docker-hub-password') {
    //def customImage = docker.build("steltix/appshare:${env.BRANCH_NAME}-${env.BUILD_ID}", "--label 'branch=${BRANCH_NAME}' .")
    //customImage.push()
    sh '''ssh -i /home/node/.ssh/id_rsa davinderk@10.126.1.6 -o "StrictHostKeyChecking no" "docker rm -f appshare-steltix-3000" '''
    sh 'ssh -i /home/node/.ssh/id_rsa davinderk@10.126.1.6 -o "StrictHostKeyChecking no" "docker run -d  -p 3000:80 -l account=steltix -l port=3000 -l owner=appshare --restart always --name appshare-steltix-3000 steltix/appshare:${env.BRANCH_NAME}-${env.BUILD_ID}"'
      //}
    }
    //sh 'tar -cvf public.tar public'
    //archiveArtifacts artifacts: 'public.tar', fingerprint: true
    //notifyBuild('Build finished','');
   }
  }
 }
 post { 
  failure {
    echo "error"
   //notifyBuild('Build error','error');
  }
 }
}

void notifyBuild(String msg , String type) {
  // Default values
  def colorName = 'RED'
  def colorCode = '#FF0000'
  def author = sh(
        script: "git --no-pager show -s --format='%an'",
        returnStdout: true
       ).trim();
  def subject = "${msg} by ${author}: '${env.JOB_NAME}'"
  def summary = "${subject} (${env.RUN_DISPLAY_URL})"
  if (type == 'info') {
    color = 'YELLOW'
    colorCode = '#FFFF00'
  } else if (type == 'error') {
    color = 'RED'
    colorCode = '#FF0000'
  } else {
    color = 'GREEN'
    colorCode = '#00FF00'
  }
  // Send notifications
  slackSend baseUrl: 'https://hooks.slack.com/services/', channel: '#appsharedeploy', color: colorCode, message: summary, tokenCredentialId: 'slack-token'
}

