def skipBuild = true
pipeline {
 agent {
        docker {
            image 'cypress/browsers:latest' 
            args '-p 3000:3000 -v /home:/home/node/ -u root'
        }
    }
 environment {
        AUTHOR = ''
    }
 stages {
  stage('Checkout') {
   steps {
    checkout scm
   }
  }
  stage('check branch') {
   steps {
    sh 'git --version'
    echo "Branch: ${env.BRANCH_NAME}"
    script {
     def GIT_LOG = sh(script: "git log --oneline -n 1 HEAD --pretty=format:%B", returnStdout: true)
     env.AUTHOR = sh(
        script: "git --no-pager show -s --format='%au'",
        returnStdout: true
       ).trim()
     def message = GIT_LOG.trim().replaceAll("\n ", "")
     echo "GIT_LOG:${message.size()} , ${GIT_LOG}"
     def deployMatch = message ==~/(?i).*deployj#.*/
     echo "deployMatch: ${deployMatch}"
     if (deployMatch || env.BRANCH_NAME == "master") {
      skipBuild = false;
     }
     echo "skipBuild: ${skipBuild}"
    }
   }
  }
  stage('Build') {
   when {
    expression {
     skipBuild == false
    }
   }
   steps {
    //notifyBuild('Build started','');
    //sh 'npm install';
    sh 'ls /home/node'
    input message: 'Finished using the web site? (Click "Proceed" to continue)'
    sh 'printenv' 
    //sh 'ssh -t davinderk@10.126.1.6'
    sh '''ssh -i /home/node/.ssh/id_rsa davinderk@10.126.1.6 -o "StrictHostKeyChecking no" cat /home/davinderk/tmp/deleteModule.js'''
    //sh 'npm run build'
    //sh 'tar -cvf public.tar public'
    
    //archiveArtifacts artifacts: 'public.tar', fingerprint: true
    //notifyBuild('Build finished','');
   }
  }
 }
 post {
  failure {
    echo "error"
   //notifyBuild('Build error','error');
  }
 }
}

void notifyBuild(String msg , String type) {
  // Default values
  def colorName = 'RED'
  def colorCode = '#FF0000'
  def author = sh(
        script: "git --no-pager show -s --format='%an'",
        returnStdout: true
       ).trim();
  def subject = "${msg} by ${author}: '${env.JOB_NAME}'"
  def summary = "${subject} (${env.RUN_DISPLAY_URL})"
  if (type == 'info') {
    color = 'YELLOW'
    colorCode = '#FFFF00'
  } else if (type == 'error') {
    color = 'RED'
    colorCode = '#FF0000'
  } else {
    color = 'GREEN'
    colorCode = '#00FF00'
  }
  // Send notifications
  slackSend baseUrl: 'https://hooks.slack.com/services/', channel: '#appsharedeploy', color: colorCode, message: summary, tokenCredentialId: 'slack-token'
}

